### ISSUE TITLE
Windows ユーザー向けのgit利用時の注意

### ISSUE THREAD

**Issue by takeshi-a** [The-Japan-DataScientist-Society/100knocks-preprocess#1]
DS100本ノックの公開、ありがとうございます。

Dockerの初心者です。Dockerのことを調べながら、インストールをしましたが、注意書きの意味がよくわからないまま、インストールしたため、ビルド時にエラーが起きました。

> ※ Windowsでgitを利用する場合、デフォルト設定でのインストールを行うとスクリプトの改行コードを変えられてしまい、データベースを正しく構築できないことがあります
> ※ 改行を変えないよう設定するか、ZIPをダウンロードして利用してください

ガイド（100knocks_guide.pdf）と下記の記事を参考にして、core.autocrlfをtrueにしないのが正しいことを知りました。
https://qiita.com/uggds/items/00a1974ec4f115616580

`git config -global core.autocrlf input`
または
`git config -global core.autocrlf false`
が適切な設定と思います。

WindowsユーザーはWindows環境で実行する場合、core.autocrlf trueが正しいですが、こちらの場合、Docker上のLinux環境で実行することから、core.autocrlf input/falseが正しいということかと思います。

初心者はそのあたりの理解が浅いので、おそらく同じようにトラブルになる人が出ると思いました。Docker初心者は先にガイドを読んで、Dockerの仕組みを理解してから、ビルド作業に入るとよさそうです。ご参考になれば幸いです。

**Comment by KazuhiroM** [comment]
ISSUEありがとうございます。READMEから当ISSUEにリンクを追加させていただきます！

**Comment by takeshi-a** [comment]
KazuhiroM さん

ISSUEを取り上げていただき、ありがとうございます。
[Start Python Club](https://startpython.connpass.com/)の[阿久津](https://twitter.com/akucchan_world)と申します。

安宅さんの[ツイート](https://twitter.com/kaz_ataka/status/1272475499562823688)を見て、こちらのレポジトリを知りました。初心者にとっては貴重な学習材料です。利用者視点でブラッシュアップに協力させてください。ほかにもISSUEがあったら、UPします。

ハッシュタグ #DS100本ノック で毎日、訓練について、つぶやきます。また私が主催しているコミュニティで開催する7/9の[オンライン勉強会](https://startpython.connpass.com/event/175454/)で紹介させていただきますので、ご了承ください。

よろしくお願いします。
