### ISSUE TITLE
P-078の解答のコメントは不要では？

### ISSUE THREAD

**Issue by twobooks** [The-Japan-DataScientist-Society/100knocks-preprocess#11]
P-078の解答コード例に
「# skleanのpreprocessing.scaleを利用するため、標本標準偏差で計算されている」
とありますが、当該コードではnp.percentileを利用しておりコメントとコードが合致していないように見受けられます。
削除が相当ではないでしょうか？

**Comment by KazuhiroM** [comment]
その前の設問からセルをコピーしてきた際に残ってしまっていたようです
Issueありがとうございます
対応しましたmm
