### ISSUE TITLE
docker toolboxで環境を構築すると、notebookを開いてすぐ閉じてしまう

### ISSUE THREAD

**Issue by chaos44** [The-Japan-DataScientist-Society/100knocks-preprocess#13]
Ｃのユーザーフォルダー内に必要のあるデータをgit cloneして
http://192.168.99.100:8888/lab?
でjupyter labを開けましたが、表示してるファイルをクリックしたら
新しいタブで一瞬だけ表示されて消えてしまいます。

**Comment by KazuhiroM** [comment]
すみません。こちらではその状況が再現できず、また個別のご質問・トラブルシューティングには対応ができない点、どうぞご了承ください。同様の事象が多く寄せられ、その発生原因が特定できた場合には、プログラムの修正含め対応を検討させていただきます。

**Comment by chaos44** [comment]
C:\Usersではなく、C:\Users\自分のユーザ名にgit cloneしたらうまくでまく開けるようになりました。
