### ISSUE TITLE
わかりづらい・不適当な問題文の変更提案

### ISSUE THREAD

**Issue by wany-oh** [The-Japan-DataScientist-Society/100knocks-preprocess#132]
問題文から想定される作業と模範解答で行っている作業が一致していないことが多々あります。特に『問題文で指示されていないことをわざわざやっている模範解答』が散見されます。こうした例は学習者にかなりの困惑と負担を与えます。
問題文の説明が不十分であるのか、模範解答のコードが冗長余剰であるのかはわかりませんが、前者だと仮定して、いくつかそうした例の紹介と修正の提案をします。

## 039

> レシート明細データフレーム（df_receipt）から売上日数の多い顧客の上位20件と、売上金額合計の多い顧客の上位20件を抽出し、完全外部結合せよ。ただし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

この問題は2つのデータフレームを作成し、その2つを結合するという作業が意図されていますが、同じデータフレーム（`df_receipt`）から抽出するためそのことがわかりづらいです（一文目だけではOR条件の抽出のようにみえる）。以下のような表現にすることを提案します。

> レシート明細データフレーム（df_receipt）から、売上日数の多い顧客の上位20件を抽出したデータフレームと、売上金額合計の多い顧客の上位20件を抽出したデータフレームをそれぞれ作成し、さらにその2つを完全外部結合せよ。ただし、非会員（顧客IDが"Z"から始まるもの）は除外すること。

## 040

> 全ての店舗と全ての商品を組み合わせると何件のデータとなるか調査したい。店舗（df_store）と商品（df_product）を直積した件数を計算せよ。

『何件のデータとなるか調査したい』『件数を計算せよ』という問題文だと、2つのデータフレームの長さの積をとるのが最適解です。この問題文で、模範解答のようにCROSS JOINする人はまずいないと思います。CROSS JOINしなさいということを問題文に書くべきです。

例えば、

>  全ての店舗と全ての商品を組み合わせたデータフレームを作成し、その件数を表示せよ。

## 041, 042

> 041: レシート明細データフレーム（df_receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、前日からの売上金額増減を計算せよ。なお、計算結果は10件表示すればよい。
> 042: レシート明細データフレーム（df_receipt）の売上金額（amount）を日付（sales_ymd）ごとに集計し、各日付のデータに対し、１日前、２日前、３日前のデータを結合せよ。結果は10件表示すればよい。

041の問題は『売上金額増減を計算せよ』となっていますが、模範解答では、１日前のデータを結合した上で金額増減も計算するという作業を行っています。これは042よりも難易度が上の作業です。
以下のどちらかの修正をすべきだと思います。

- 041を『１日前のデータを結合した上で、前日からの売上金額増減を計算せよ』というような問題文に変更し、042と出題順を入れ替える。
- 041の模範解答から１日前のデータを結合する作業を消す。

## 043

> レシート明細データフレーム（df_receipt）と顧客データフレーム（df_customer）を結合し、性別（gender）と年代（ageから計算）ごとに売上金額（amount）を合計した売上サマリデータフレーム（df_sales_summary）を作成せよ。性別は0が男性、1が女性、9が不明を表すものとする。
>
> ただし、項目構成は年代、女性の売上金額、男性の売上金額、性別不明の売上金額の4項目とすること（縦に年代、横に性別のクロス集計）。また、年代は10歳ごとの階級とすること。

これが最も難解な問題文でした。

まず顧客データフレーム（`df_customer`）には、性別を表す列として、｛男性, 女性, 不明｝からなる`gender`列と、｛0, 1, 9｝からなる`gender_cd`列という2つがあります。ここで、問題文には『性別（**gender**）』とあるにもかかわらず、模範解答では`gender_cd`列が使われているのは奇妙です。

次に一行目末尾の文章『性別は0が男性、1が女性、9が不明を表すものとする。』というのが、一見すると何の話かわかりません。これは`gender_cd`列の説明と思われますが、他の問題文と比較すると、出力すべき結果のデータフレームにおいて性別を｛0, 1, 9｝で表現しろといっているように聞こえます。また模範解答では｛0, 1, 9｝を｛male, female, unknown｝に変更していますが、逆にこの作業は問題文には書かれていません。

以下修正例です。

> レシート明細データフレーム（df_receipt）と顧客データフレーム（df_customer）を結合し、性別（gender_cd）と年代（ageから計算）ごとに売上金額（amount）を合計した売上サマリデータフレーム（df_sales_summary）を作成せよ。
> ただし、項目構成は年代、女性の売上金額、男性の売上金額、性別不明の売上金額の4項目とすること（縦に年代、横に性別のクロス集計）。
> なお、gender_cd列は0が男性、1が女性、9が不明を表しているが、それぞれmale、female、unknownに変更すること。また、年代は10歳ごとの階級とすること。

## 055

> レシート明細データフレーム（df_receipt）の売上金額（amount）を顧客ID（customer_id）ごとに合計し、その合計金額の四分位点を求めよ。その上で、顧客ごとの売上金額合計に対して以下の基準でカテゴリ値を作成し、顧客ID、売上金額合計とともに表示せよ。カテゴリ値は上から順に1〜4とする。結果は10件表示させれば良い。
>
> - 最小値以上第一四分位未満
> - 第一四分位以上第二四分位未満
> - 第二四分位以上第三四分位未満
> - 第三四分位以上

pythonのみ模範解答が2つ用意されていますが、2つ目の解答は問題文の『カテゴリ値は上から順に1〜4とする』『結果は10件表示』を満たしていません。056問目のように『年代を表すカテゴリ名は任意とする』のように修正するか、模範解答を修正するかはおまかせします。

## 共通

『10件表示』させる問題がたくさんありますが、問題によって表現が異なるのが気になります。（作問者が違うのでしょうか）

> 10件だけ表示せよ。
> 10件表示させよ。
> 10件表示せよ。
> 結果は10件表示させれば良い。
> 先頭10件を表示させればよい。
> データは10件だけ表示させれば良い。
> データは10件を抽出すれば良い。

細かい書き方の違いはともかく、『せよ』と『すれば良い』が混ざっているのはかなり気になります。

## その他

新しくデータフレームを作成したり、列を追加したりするような問題で、Python、R、SQLそれぞれの模範解答で変数名や列名が異なっているものがあります。例えば055問目ではカテゴリ値を表す列がPythonの模範解答は`pct_group`、Rの模範解答は`amount_cat`、SQLの模範解答は`pct_flg`となっています。
確かに、043問目（`df_sales_summary`）等一部を除いて、変数名や新規列名を何にするかは問題文で指定されていませんが、模範解答では一致させたほうがよいと思います。PythonをマスターしているがRに移行しようと思っているユーザーは両者を見比べるかもしれません。

**Comment by KazuhiroM** [comment]
ご提案ありがとうございます！手弁当でつくったところもあり、細かいところで統一とれていないところや、設問で書かれている項目と解答例で使っている項目に差異があるなど確かにあり、ご提案を可能な範囲で取り込ませていただきます。

クロス結合とはテーブルの直積である、という知識を問うためにわざとこう書いているところもあったり、いくつかは意図して記載しているものもありますので、そのまま残すものもあるかもですがご了承ください。

問題で求められている以上のことを解答例でやっている点も、かならずしも解答コードが唯一の答えではなく、ある程度自由度があって良いと考えております。解答例と同じことをやっていないからだめ、というコンテンツではないので、ここはどこまで対応するかは可能な範囲とさせてください（逆に学習者にとって、こういう処理が書けるんだと学びになるようなコード例がなくなるのはさけたいです）。

また、必ずしも難易度順に並べているわけではない（野球のノックのようにいろんなところにボールが飛んでくる）点もご理解いただけば幸いです。

**Comment by KazuhiroM** [comment]
書籍化の一環でできる限りの表記統一と説明文の変更を行いました。一旦クローズさせていただきます。
