### ISSUE TITLE
P-076の回答例

### ISSUE THREAD

**Issue by hyga2c** [The-Japan-DataScientist-Society/100knocks-preprocess#15]
結果は変わりませんが、下記のとおりt`rain_test_split`の層化抽出のパラメータをgender_cdで指定、`groupby`でgenderを指定した方が設問の意図に沿っている様に考えますが、いかがでしょうか。
```
_, df_tmp = train_test_split(df_customer, test_size = 0.1, stratify=df_customer['gender_cd'])
df_tmp.groupby('gender').agg({'customer_id':'count'})
```

**Comment by KazuhiroM** [comment]
おっしゃるとおり、設問でgender_cdと書いているので、genderよりもgender_cdの方が良いですね。イージーミスしました
ご指摘ありがとうございます！
