### ISSUE TITLE
P-047の問題文と回答例が合っていない

### ISSUE THREAD

**Issue by ToshihideMatsuda** [The-Japan-DataScientist-Society/100knocks-preprocess#152]
preprocess_knock_Python.html の` P-047`の問題文の問題文の売上エポック秒（`sales_epoch`）と、
回答例の`df_receipt['sales_ymd']`が合っていないように見えます。

> P-047: レシート明細データ（df_receipt）の売上エポック秒（sales_epoch）は数値型のUNIX秒でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

           pd.concat([df_receipt[['receipt_no', 'receipt_sub_no']],
           pd.to_datetime(df_receipt['sales_ymd'].astype('str'))],
          axis=1).head(10)

後続に類似問題として`P-048`があり、こちらと混同されているように見えます。

>P-048: レシート明細データフレーム（df_receipt）の売上エポック秒（sales_epoch）は数値型のUNIX秒でデータを保有している。これを日付型に変換し、レシート番号(receipt_no)、レシートサブ番号（receipt_sub_no）とともに10件表示せよ。

           pd.concat([df_receipt[['receipt_no', 'receipt_sub_no']],
           pd.to_datetime(df_receipt['sales_epoch'], unit='s').rename('sales_ymd')], 
           axis=1).head(10)

**Comment by KazuhiroM** [comment]
ありがとうございます！多分編集ミスしたようです。早めに対応します！
