### ISSUE TITLE
R-015の解答、誤植？

### ISSUE THREAD

**Issue by TakahiroMihara** [The-Japan-DataScientist-Society/100knocks-preprocess#2]
R-015: 顧客データフレーム（df_customer）から、ステータスコード（status_cd）の先頭がアルファベットのA〜Fで始まり、末尾が数字の1〜9で終わるデータを全項目抽出し、10件だけ表示せよ。
解答（answer）
head(df_customer %>% filter(grepl("^[A-Z].*[1-9]$", status_cd)), n=10)

上記の[A-Z]は問題に沿うと[A-F]だと思いました。

**Comment by KazuhiroM** [comment]
Issueありがとうございます。現在、コード例の別解を追加するなどの検討もしていますので、合わせて取り込ませていただきます。

**Comment by KazuhiroM** [comment]
対応いたしましたのでクローズさせていただきます。

**Comment by KazuhiroM** [comment]
対応いたしましたのでクローズさせていただきます。
