### ISSUE TITLE
P-031.pandas.Series.std() と numpy.std() におけるddof引数のデフォルト値の違い

### ISSUE THREAD

**Issue by KazumaWadaTPD** [The-Japan-DataScientist-Society/100knocks-preprocess#20]
P-031の回答において、この問題はPandasの関数を使用する際の注意点を気づかせる問題としてとても良い問題だと思います。
Pandasとnumpyにおいて同じstd()でも引数のデフォルトの値が違います。この問題はエラーが出ることも無いので気づかないまま利用する事もありとても危険です。
Pandas：
DataFrame.std(self, axis=None, skipna=None, level=None, ddof=1, numeric_only=None, **kwargs)
Numpy:
numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
この違いを回答に明記する事によって、学習者に危険性を知らせると親切であると思います。

**Comment by KazuhiroM** [comment]
高度な示唆ありがとうございます！確かに、とても重要な知識ですね！numpyとpandasで違うこと、回答例の中のコメント文で紹介させていただきます

**Comment by KazuhiroM** [comment]
TIPSとしてansファイルに追記しました。GitHubにアップしたら一旦クローズさせていただきます。

**Comment by KazumaWadaTPD** [comment]
対応いただきましてありがとうございます。
