### ISSUE TITLE
PipfileにてSQLAlchemyのバージョンを固定したい

### ISSUE THREAD

**Issue by takahiro9** [The-Japan-DataScientist-Society/100knocks-preprocess#201]
## 事象

- preprocess_knock_SQL.ipynb で[このコード](https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/blob/master/docker/work/preprocess_knock_SQL.ipynb?short_path=1bf6a22#L39-L52)を実行時に `MetaData.__init__() got an unexpected keyword argument 'bind'` が出力され、クエリが実行できない

<img width="1055" alt="スクリーンショット 2023-02-19 20 34 52" src="https://user-images.githubusercontent.com/3500702/219945359-a72d298d-237d-4ea7-83bf-61e458f61a46.png">

## 判明していること

- [sqlalchemy](https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/blob/master/Pipfile.lock#L350-L395) はメジャーバージョン2系を利用している
- sqlalchemyに依存する[ipython-sqlは2系に対して互換性がない](https://github.com/catherinedevlin/ipython-sql/commit/cc4633cd3367cc0eecc48e48c9430c988cd11eac)

## 提案

[Pipfile](https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/blob/master/Pipfile)に下記を追記してはどうでしょうか

```
SQLAlchemy = "==1.4.46"
```

## 補足

「データサイエンス100本ノック構造化データ加工編ガイドブック」で学習させてもらっております。
仕事に活かせればと思いながら読んでおります。執筆いただきありがとうございます。

**Comment by massongit** [comment]
📝 https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/pull/198 でsqlalchemyが2系になっている。

**Comment by massongit** [comment]
報告ありがとうございます。
こちら修正しました。

**Comment by KazuhiroM** [comment]
報告ありがとうございました！
