### ISSUE TITLE
[bug]Category-Tableの表示間違い(ER図に関して)

### ISSUE THREAD

**Issue by TP-hiroyuki** [The-Japan-DataScientist-Society/100knocks-preprocess#21]
@KazuhiroM  様

学習にとても便利な資料の作成ありがとうございます。
以下、気になる点がありましたので、ご報告いたします。

100knocks-preprocess-master\docker\doc\100knocks_ER.pdfのページ1に関して。
テーブル：カテゴリ（category）テーブル
場所：3行目「カテゴリ⼤区分コード」、4行目「カテゴリ⼤区分名」
修正後：「カテゴリ中区分コード」、「カテゴリ中区分名」

の間違いではないかと指摘させていただきます。

ご確認のほどどうぞよろしくお願いいたします。

**Comment by KazuhiroM** [comment]
ありがとうございます！確認し、適宜対応します！

**Comment by KazuhiroM** [comment]
categoryテーブルのデータ構造よろしくない件とも関わるので、一度openに戻させていただきますmm
