### ISSUE TITLE
003問の誤記

### ISSUE THREAD

**Issue by rootassist** [The-Japan-DataScientist-Society/100knocks-preprocess#228]
003の問題文で"sales_ymdをsales_dateに"となるべき箇所が"sales_ymdsales_dateに"となっております。("を"が抜けている)
Pythonの"preprocess_knock_Python.ipynb"以外の(ansを含めた)5ファイルに該当の誤記が存在しています。おそらく修正漏れではないかと思います。

**Comment by KazuhiroM** [comment]
ありがとうございます。修正漏れのようです。
