### ISSUE TITLE
[enhancement(P-059)] 回答の追記提案 (queryのengineについて)

### ISSUE THREAD

**Issue by TP-hiroyuki** [The-Japan-DataScientist-Society/100knocks-preprocess#24]
@KazuhiroM  様

使いやすい資料の作成と共有ありがとうございます。
以下、気になる点がございましたので、ご確認のほど、よろしくお願いいたします。

【提案内容】
環境によって、以下デフォルトの式処理が変わる事を明記し、学習者に危険性を知らせると親切であると思います。

【追記提案詳細】
query()の引数engineで'python'か'numexpr'かを選択でき、デフォルトはインストールされていればnumexprが、無ければpythonが使われます。
さらに、文字列メソッドはengine='python'でないとquery()メソッドで使えません。

ご勘案のほど、よろしくお願いいたします。

**Comment by KazuhiroM** [comment]
とてもディープな示唆、ありがとうございます。
回答例のコメントで掲載させて頂きます。

**Comment by KazuhiroM** [comment]
TIPSとしてansファイルに追記しました。GitHubにアップしたら一旦クローズさせていただきます。
