### ISSUE TITLE
「はじめに」 のインポート時にエラー

### ISSUE THREAD

**Issue by nakazono1011** [The-Japan-DataScientist-Society/100knocks-preprocess#25]
大変有益な資料の公開ありがとうございます。

Windows10 Home クライアント環境でDocker Tool を利用して環境構築を行い、
「preprocess_knock_Python.ipynb」 で１００本ノックを行おうとしたところ、
はじめに のセルを実行した際に、下記のエラーが発生し、先に進めない状況です。
環境構築のやり方が間違っているのかと何度も構築しなおしてみましたが解決できずじまいです。

> `FATAL:`  password authentication failed for user "padawan"

色々いじって、UserとPASSWORDを「postgres」・「postgres12345」に手動で変更したところ、うまく接続できたみたいですが、今度はSQL文の中のテーブルが存在しない旨のエラーが発生しました。。

同じエラーが発生して解決した方いらっしゃったらご教示いただけると幸いです。

**Comment by KazuhiroM** [comment]
DB構築スクリプトがうまく動いていないのかもしれません。改行コードの問題でDB構築がうまくいかないときもありますので、今一度ドキュメントやREADMEを参考にしていただければと思います。

**Comment by nakazono1011** [comment]
ご回答ありがとうございます。
私も最初そこを疑ってZIP経由で環境構築を行いましたが結果は変わらずでした。
取り急ぎ、CSVをインポートする形で演習を進めています。
この問題についてまた進展がありましたら教えて頂けると幸いです。

**Comment by KazuhiroM** [comment]
管理上、一旦クローズします。もし事象の再現パターンが特定できましたら、再度Issueを上げていただければと思います。また、こちらで解決方法の可能性がある情報など入ってきましたらREADMEなどに記載していきます。

**Comment by KazuhiroM** [comment]
データベースの構築がうまく行かない場合、gitのbashプロンプトからコンテナ作成をするとうまくいく、という報告が見られます。READMEに追記しました。
