### ISSUE TITLE
R-029とS-029の解答例で、複数ある最頻値の内1つしか取得できていない

### ISSUE THREAD

**Issue by eitsupi** [The-Japan-DataScientist-Society/100knocks-preprocess#32]
P-029の解答例では店舗コードS13051とS14036が複数行ありますが、R-029とS-029ではそれぞれ一行になってしまっています。
P-029のようにすべて列挙されるようになっていた方が良いように思います。

↓（参考）R-029の私の解答

```R
df_receipt %>%
  group_by(store_cd, product_cd) %>%
  summarise(n = n(), .groups = 'drop_last') %>%
  filter(n == n %>% max()) %>%
  ungroup()
```

↓出力

A tibble: 55 × 3

store_cd <chr> | product_cd <chr> | n <int>
-- | -- | --
S12007 | P060303001 | 72
S12013 | P060303001 | 107
S12014 | P060303001 | 65
S12029 | P060303001 | 92
S12030 | P060303001 | 115
S13001 | P060303001 | 67
S13002 | P060303001 | 78
S13003 | P071401001 | 65
S13004 | P060303001 | 88
S13005 | P040503001 | 36
S13008 | P060303001 | 77
S13009 | P060303001 | 64
S13015 | P071401001 | 34
S13016 | P071102001 | 32
S13017 | P060101002 | 31
S13018 | P071401001 | 47
S13019 | P071401001 | 70
S13020 | P071401001 | 79
S13031 | P060303001 | 115
S13032 | P060303001 | 85
S13035 | P040503001 | 39
S13037 | P060303001 | 88
S13038 | P060303001 | 41
S13039 | P071401001 | 36
S13041 | P071401001 | 70
S13043 | P060303001 | 56
S13044 | P060303001 | 96
S13051 | P050102001 | 5
S13051 | P071003001 | 5
S13051 | P080804001 | 5
S13052 | P050101001 | 4
S14006 | P060303001 | 70
S14010 | P060303001 | 68
S14011 | P060101001 | 51
S14012 | P060303001 | 142
S14021 | P060101001 | 30
S14022 | P060303001 | 71
S14023 | P071401001 | 70
S14024 | P060303001 | 96
S14025 | P060303001 | 46
S14026 | P071401001 | 40
S14027 | P060303001 | 152
S14028 | P060303001 | 140
S14033 | P071401001 | 68
S14034 | P060303001 | 71
S14036 | P040503001 | 19
S14036 | P060101001 | 19
S14040 | P060303001 | 80
S14042 | P050101001 | 34
S14045 | P060303001 | 33
S14046 | P060303001 | 71
S14047 | P060303001 | 36
S14048 | P050101001 | 17
S14049 | P060303001 | 55
S14050 | P060303001 | 9

**Comment by KazuhiroM** [comment]
ご指摘ありがとうございます。言語間でのmodeの仕様の違いでしょうか。
できれば揃えたいのですが、SQLが逆にMODE()関数が使えなくなりそうなので、MODE()関数の存在も知見として残しておきたいので、
- Rは頂いたコードで置き換え
- SQLは結果が重複して出るコードを加えながら、mode()を使った簡易版の参考コードとして今のコードも残す

という方針で検討してみます。

**Comment by KazuhiroM** [comment]
対応いたしましたのでクローズいたします。
