### ISSUE TITLE
P-061/R-061/S-061解答例　amount+1の必要性？

### ISSUE THREAD

**Issue by eitsupi** [The-Japan-DataScientist-Society/100knocks-preprocess#33]
061の解答例で、いずれの言語でも`amount`列に+1したものにlog関数を適用しているのですが、これは正しい処理でしょうか？
例えば解答例出力1行目の`amount`列1298に対して`amount_log10`列は3.113609となっていますが、amount+1せずにlog関数を使うと出てくる3.113275と比べると

```R
> 10^3.113609
[1] 1299
> 10^3.113275
[1] 1298.001
```

となり、amount+1した方は1298からズレてしまっています。
+1は不要ではないでしょうか？

**Comment by KazuhiroM** [comment]
対数化する際にlog(0)を回避するために1やもっと小さい数字を足すというのはよくやられる方法となります。本当はもっと小さな数字を足すのが良いという考え方もあるようですが、本ノックが初学者向けであること、多くの書籍でlog(x+1)で記載されることが多いことから、ここでは１を足しています。前処理として分布の形を変えるための対数化としてはよくやられる方法です（バグではないため、一旦管理上クローズいたします）。

**Comment by eitsupi** [comment]
@KazuhiroM ご回答ありがとうございました。納得しました。
