### ISSUE TITLE
レシート明細テーブル（receipt）の売上日（sales_ymd）と売上エポック秒（sales_epoch）がずれている

### ISSUE THREAD

**Issue by dfukagaw28** [The-Japan-DataScientist-Society/100knocks-preprocess#35]
教材のご提供ありがとうございます。

P-047 と P-048 の解答例をみると，それぞれ 9 年ずれています。

P-047
receipt_no | receipt_sub_no | sales_ymd
-- | -- | --
112 | 1 | 2018-11-03
1132 | 2 | 2018-11-18
1102 | 1 | 2017-07-12

P-048
receipt_no | receipt_sub_no | sales_epoch
-- | -- | --
112 | 1 | 2009-11-03
1132 | 2 | 2009-11-18
1102 | 1 | 2008-07-12

receipt.csv のどちらかの列が誤っているのだろうと思います。

sales_epoch の方は途中で 1 日抜けがありますので，おそらく sales_ymd の方が正しいのでしょうか？

**Comment by KazuhiroM** [comment]
ベースとしたデータの日付が古かったので近年の日付に置き換えた際、エポック秒の更新に漏れがあったかもです。早めに対応します。

**Comment by KazuhiroM** [comment]
対応しました。CSVファイルをご指摘を踏まえ修正し、また出力結果に関わるため回答のnotebookとhtmlも更新しています。
ノック環境はPostgreSQLからデータを取得しているため、反映はコンテナの再作成が必要となる点、ご了承ください。
