### ISSUE TITLE
テーブルreceiptのキーの不整合

### ISSUE THREAD

**Issue by twofacauth** [The-Japan-DataScientist-Society/100knocks-preprocess#36]
ER図によるとテーブルreceiptのPKがsales_ymd, receipt_no, receipt_sub_noの複合になっていますが、実際にはそうなっていないデータがあります。
たとえば
sales_ymd = 20170101 and receipt_no = 1102
のケースで、該当するのが以下のレコードになっています。
![image](https://user-images.githubusercontent.com/58118175/95775086-aab1c100-0cfc-11eb-962b-70f318c6e47d.png)
取引数を直接計算する設問はないようですが、データとして紛らわしいのでreceipt_noを分けたほうがいいと思いました

**Comment by KazuhiroM** [comment]
実務ケースを考えると、POSレジでレシート番号が発行されることを考えればお店もPKに入れるのが正しいですね。ER図を修正しておきます！

**Comment by KazuhiroM** [comment]
実際、Docker環境構築時に走るCREATE TABLEは以下のようにしていました。

 -- receipt
    drop table if exists receipt;
    create table receipt(
      sales_ymd       INTEGER,
      sales_epoch     INTEGER,
      store_cd        VARCHAR(6),
      receipt_no      SMALLINT,
      receipt_sub_no  SMALLINT,
      customer_id     VARCHAR(14),
      product_cd      VARCHAR(10),
      quantity        INTEGER,
      amount          INTEGER,
      primary key (sales_ymd, store_cd, receipt_no, receipt_sub_no)
    );

こちらに合わせ、ER図を修正しておきます。

**Comment by KazuhiroM** [comment]
ER図を修正しました。クローズさせていただきます。
