### ISSUE TITLE
ER図（100knocks_ER.pdf）一部フィールドの型について

### ISSUE THREAD

**Issue by sp6** [The-Japan-DataScientist-Society/100knocks-preprocess#37]
ER図（docker/doc/100knocks_ER.pdf）について
docker/db/init/2_create_table.sh で指定されている型と対応していない箇所があるように思います。
2_create_table.shにあわせると以下ではないでしょうか。

顧客（customer）
　名前（customer_name）数値 => 文字列

レシート明細（receipt）
　売上エポック秒（sales_epoch） 文字列 => 整数？
　レシート番号（receipt_no） 文字列 => 整数？
　レシートサブ番号（receipt_sub_no） 文字列 => 整数？

**Comment by KazuhiroM** [comment]
ご指摘ありがとうございます。確認の上、適宜対応いたします！

**Comment by KazuhiroM** [comment]
対応いたしました。コピペミス多く恐縮ですm(_ _)m
ご指摘感謝です！
