### ISSUE TITLE
csvデータgeocode.csvの項目名latitude

### ISSUE THREAD

**Issue by rjnemoto** [The-Japan-DataScientist-Society/100knocks-preprocess#38]
csvデータgeocode.csvの1行目の項目名latitudeについて、項目名とその前のカンマの間にスペースがあります。

データだけを利用させて頂いてPythonの軽量の環境を作っていたときに、pandas.read_csvで失敗するために気がつきました。

ただし、ご提供頂いたDocker環境では問題になりませんし、この失敗への対策も含めて「課題」である、とも考えられますから、更新されるかどうかについてはご判断にお任せしたいと思います。

**Comment by KazuhiroM** [comment]
CSV直接活用もありかと思いますので対応したいと思います。

本件の発見、とてもありがたいです！

**Comment by KazuhiroM** [comment]
対応しました。クローズさせていただきます。
