### ISSUE TITLE
windows home で環境構築

### ISSUE THREAD

**Issue by POCHI-CUTE** [The-Japan-DataScientist-Society/100knocks-preprocess#39]
無知ながら質問の方失礼します。
CPU Ryzen5系を使用しており、その関係でDoker toolboxのv18.03.0のものを使用しています。しかしながらdocker-compose upでコンテナの作成をしようとするも「ERROR: Service 'notebook' failed to build:」などのエラーが出て作成できませんでした。100本ノックはDocker toolboxの最新版v19にしか対応していないのでしょうか。
CPUがintelのPCで試してみます。

**Comment by KazuhiroM** [comment]
最新版でのみ動作確認しております。ご了承下さいmm

**Comment by KazuhiroM** [comment]
PythonやRの学習であれば、Dockerを立ち上げなくともCSVファイルを直接ロードすることで学習できます。ご検討下さいmm

**Comment by KazuhiroM** [comment]
また、Home Editionの場合は他にもビルドでコケるケースがあるようなので、バージョン以外の可能性含め調査すると良いかと思います。

原則、質問対応は厳しいのでクローズとさせてください。

**Comment by POCHI-CUTE** [comment]
お忙しい中ご返信ありがとうございます。
CSVファイルを直接ロードして行いたいと思います。
