### ISSUE TITLE
P-072の解答例で drop_duplicates() がない

### ISSUE THREAD

**Issue by takeshi-a** [The-Japan-DataScientist-Society/100knocks-preprocess#4]
P-070～074は2つのデータフレームを内部結合して、経過した年月日を求める点が共通しています。
いずれも内部結合したときに生じる重複データを削除していますが、P-072解答例のみ
```python
df_tmp = df_tmp.drop_duplicates()
```
が省略されています。
データの重複を削除する方が適切なように見えますが、いかがでしょうか？
ご確認のほど、よろしくお願いいたします。

**Comment by KazuhiroM** [comment]
ご指摘ありがとうございます！確認の上、対応させていただきます！

**Comment by KazuhiroM** [comment]
対応いたしましたのでクローズさせていただきます。
