### ISSUE TITLE
P-089解答 重複したデータ

### ISSUE THREAD

**Issue by Kosuke-KIDO** [The-Japan-DataScientist-Society/100knocks-preprocess#40]
P-089の解答では、重複したデータが含まれると思いますが良いのでしょうか。
train_test_splitでの分割前にdrop_duplicates()など不要でしょうか。

**Comment by KazuhiroM** [comment]
ご指摘ありがとうございます。そのとおりですね。RとSQLは事前にcustomerでgroup byなどしていましたが、Pythonではその処理が漏れていました。ご提案いただいたdrop_duplicates()でももちろん問題ないかと思いますが、結合件数をへらすために先にgroupbyする形で回答ファイルを修正しました。
