### ISSUE TITLE
エラーのご相談：OperationalError: FATAL:  password authentication failed for user "padawan"

### ISSUE THREAD

**Issue by ryota0918** [The-Japan-DataScientist-Society/100knocks-preprocess#42]
100本ノックに取り組もうとしたところ、初めの部分でこのようなエラーが出てしまいました。
解決策はありますか？

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-1-8ae959333cf8> in <module>
     22 
     23 # pd.read_sql用のコネクタ
---> 24 conn = psycopg2.connect(**pgconfig)
     25 # pd.to_sql用のcreate engine
     26 engine = create_engine(dsl)

/opt/conda/lib/python3.8/site-packages/psycopg2/__init__.py in connect(dsn, connection_factory, cursor_factory, **kwargs)
    125 
    126     dsn = _ext.make_dsn(dsn, **kwargs)
--> 127     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    128     if cursor_factory is not None:
    129         conn.cursor_factory = cursor_factory

OperationalError: FATAL:  password authentication failed for user "padawan"
```

**Comment by KazuhiroM** [comment]
こちらではWindows10 ProとMacの2機で確認しましたが、再現しませんでした。
データベースがうまく作られていないようにも見受けられますが、Windows10の場合はGitをつかう場合、インストール時にcheckoutとcommitをそれぞれas-isで行うようにしないと改行コードが変えられてしまい、うまくDBが作成されません（README参照）。もしそのようにインストールしていないなら、GitHubからZIPで取得して環境を構築してみてください。

また同じくWindows10の場合は、コンテナ作成時にフォルダ共有の許可を求めるウィンドウが表示されますが、この際にShare itを押さないとDB作成スクリプトがDocker内のLinuxと共有されず、やはりDB作成に失敗することがあります。共有できているかの確認はガイドのPDFを参考にしてみてください。

**Comment by KazuhiroM** [comment]
あと、GitHubから取得したファイル群はホームディレクトリ配下に格納するとDockerの余計な設定が不要になり楽です。

**Comment by KazuhiroM** [comment]
もしWindows10 Homeをご利用の場合は、こちらの記事がとても丁寧に記載してくれているので参考にしてみてください（フォルダ共有の設定など）。
https://qiita.com/syuki-read/items/714fe66bf5c16b8a7407

**Comment by KazuhiroM** [comment]
また、Windows10の場合、READMEで紹介させていただいている動画サイトのコメント欄で同じ事象の相談と解決が記載されています。

https://www.youtube.com/watch?v=mh8Z5d0-0PU

こちらは一度Dockerをインストールし直したらうまくいったとのことです（おそらく、始めてコンテナを作成したときにフォルダの共有許可を求めるポップアップが何かしらの理由で出なかったか、もしくは誤って許可しないを押してしまったかだと思います。その場合、フォルダ共有設定が必要となります）。

一旦、私の方で想像できる対応策は以上となりますmm

**Comment by KazuhiroM** [comment]
とりあえず提供スクリプト群の不具合ではなさそうなこと、また利用に関する個別対応は困難であることから、一旦クローズさせていただきますmm
