### ISSUE TITLE
SQL編にてDB接続で失敗する

### ISSUE THREAD

**Issue by ritalin** [The-Japan-DataScientist-Society/100knocks-preprocess#45]
* OS: MacOS Catallina 10.15.7
* Docker: Docker Desktop 3.0.2

`README`に従い、イメージのビルドは問題なかったのですが、
`jupyter`のページを開き、`DB`接続を行おうとしたところ接続できないとのエラーが表示されました。

`docker ps -a`でプロセスを確認したところ、`dss-notebook`はちゃんと起動していましたが、 `dss-postgres`イメージだけが終了していました。

`docker-compose.yml`の内容には特に不審な点が見当たらないため、原因は不明です。

`work around`として、以下のようにそれぞれのイメージを以下の順に個別に起動することで、両方のイメージの起動が確認できました。

```
docker-compose up -d dss-postgres
docker-compose up -d dss-notebook
```

また、この状態で、DB接続も問題なく行えました。

```
docker-compose up -d
```

で、起動した時、`dss-postgres`が終了してしまうことに何か心当たりはありますでしょうか？

**Comment by KazuhiroM** [comment]
こちらでは現時点のリポジトリ最新版で動作確認してみましたが、そのような事象は発生しませんでした。
Windowsを中心にそのような事象が発生しており、100knocks_guide.pdfの注意事項やReadmeでリンクを貼っている各種解説サイトなど参考にしてみてください。

**Comment by KazuhiroM** [comment]
あ、すみません。個別に起動するとうまくいくのですね。。。
はじめて聞く事象です。こちらではdocker-compose up -dで両方立ち上がっております。
もし個別起動で上手くいくようでしたら、恐縮ですがそれで運用をお願いします。

**Comment by KazuhiroM** [comment]
こちらではDocker 3.1.0です。OSは同じくCatalina 10.15.7ですので、もし可能でしたらDockerのバージョンを上げていただければ上手くいくかもしれません。

**Comment by KazuhiroM** [comment]
こちらで再現できないこと、一ヶ月ほどその後進展がないことから、一旦クローズさせていただきます。
