### ISSUE TITLE
P-084 解答例: 余分なセルがありました

### ISSUE THREAD

**Issue by takeshi-a** [The-Japan-DataScientist-Society/100knocks-preprocess#5]
[P-084 解答例](https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/blob/master/docker/work/answer/ans_preprocess_knock_Python.ipynb) のうち、以下のコードは、誤ってP-083のコードの一部が残されてしまったようです。
```python
df_product_4.isnull().sum()
```
細かいですが、ご確認のほど、よろしくお願いいたします。

**Comment by KazuhiroM** [comment]
ありがとうございます。確認の上適宜対応します。

**Comment by KazuhiroM** [comment]
df_product_4ではなくdf_tmpがただしいですね。しかし、そもそもコード例にNaN対応が入っていないようです。その点含め、対応したものを後日反映させます。

**Comment by KazuhiroM** [comment]
対応いたしましたのでクローズさせていただきます。
