### ISSUE TITLE
CIが通ることをPRマージの必須条件にする

### ISSUE THREAD

**Issue by massongit** [The-Japan-DataScientist-Society/100knocks-preprocess#58]
masterブランチに対して `Require status checks to pass before merging` を有効にすることで、CI `docker_build` や CI `Lint Code Base` ( https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/pull/54 マージ後) が通らないとPRをマージできないようにします。
この設定を適用することで、壊れたコードがマージされにくくなります。

手順: https://docs.github.com/ja/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by KazuhiroM** [comment]
🙆

**Comment by massongit** [comment]
こちらを有効にした場合、CIに関する差分を取り込んでいないPRをマージできなくなるので、設定有効後、対象のPRに対して、masterをマージするよう呼びかける必要があります。

**Comment by KazuhiroM** [comment]
> 対象のPRに対してmasterをマージするよう呼びかける必要があります。
これって具体的にどう進めるのがお作法でしょう？
READMEに書く？

**Comment by massongit** [comment]
今出されている各PRにmasterをマージしてくださいねとコメントするのが良いかと思います。

**Comment by KazuhiroM** [comment]
承知しました。現在、他から頂いているのは残り1つなのですが、こちら取り込む必要性がありそうかPRくださった方とやりとりしているので、まずはそれが済んでから設定しますね。

**Comment by KazuhiroM** [comment]
以下２つ、設定しました。他やったほうが良さそうなものとかありますでしょうか？

Require pull request reviews before merging（必要なレビュワー数は1で設定）
Require status checks to pass before merging

**Comment by massongit** [comment]
一旦はそちらの2つで良さそうかと。

**Comment by KazuhiroM** [comment]
承知しました。一旦、これでクローズさせていただきます。
