### ISSUE TITLE
Dependabotのセキュリティーアップデート有効化

### ISSUE THREAD

**Issue by massongit** [The-Japan-DataScientist-Society/100knocks-preprocess#59]
Dependabotのセキュリティーアップデートを有効化することで、脆弱性があるパッケージがあった場合、パッチが当てられたバージョンへのアップデートのPRが自動的に作成されるようになります。
これにより、脆弱性に対する対応を行いやすくなるかと思います。

手順: https://docs.github.com/ja/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates

**Comment by KazuhiroM** [comment]
#58 と合わせて実施します！

**Comment by KazuhiroM** [comment]
こちらも対応しました。

**Comment by KazuhiroM** [comment]
こちらも一旦クローズさせていただきます。
