### ISSUE TITLE
pd.read_sqlでの顧客データフレーム（df_customer）読み込み時のbirth_dayの型指定

### ISSUE THREAD

**Issue by hyga2c** [The-Japan-DataScientist-Society/100knocks-preprocess#6]
現在の読み込みではbirth_dayがstrで読み込まれています。（Rではdate形式になっている）
このため、P-045の回答では`pd.to_datetime`でdatetime形式に変換後、再度`.dt`で文字列に変換されています。
問題の意図にそったDataFrameにするためにも読み込み時にbirth_dayをparse_dates指定でdtype='datetime64'として読み出した方がよいのではないですか？

``df_customer = pd.read_sql(sql='select * from customer', con=conn, parse_dates={'birth_day'})
``

これによりP-045は下記で回答でき、問題の意図に沿ったものになると考えます。

``pd.concat([df_customer['customer_id'], df_customer['birth_day'].dt.strftime('%Y%m%d')], axis =1).head(10)
``

**Comment by KazuhiroM** [comment]
Issueありがとうございます。単純に読み込んだ状態をスタート地点として、そこから必要となる様々な手間（to_datetimeなど）を駆使することも狙って作っております。本来の分析やシステム開発では、ご指摘のように入り口で指定し、全体をシンプルにするのが良いかと思いますが、ここでは100本ノックという性質上、コード毎の手間を含め訓練として残してありますので、その点ご了承いただければと思います。

**Comment by KazuhiroM** [comment]
Wikiネタとしてピン留めし、Issueとしては一旦クローズ
