### ISSUE TITLE
リポジトリを論文で引用できるようにする

### ISSUE THREAD

**Issue by massongit** [The-Japan-DataScientist-Society/100knocks-preprocess#64]
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files?fbclid=IwAR2KPTLsB9-i9KJID11MdN9IB52r3V4y_krBB2XrjJDSEL-5MSaoZssdeR4

`CITATION.cff` を配置し、本リポジトリを論文で引用できるようにします。

**Comment by KazuhiroM** [comment]
こちら、別途やりとりさせていただいた通り一旦クローズさせていただきます。
