### ISSUE TITLE
S-038 解答中の`ORDER BY customer_id`は不要ではないでしょうか

### ISSUE THREAD

**Issue by 9sako6** [The-Japan-DataScientist-Society/100knocks-preprocess#8]
S-038 の解答では、結果が `customer_id` で昇順に並べられています。
しかし、問題文中にはそのように表示せよとの指示がありません。

他の言語の解答では昇順に並んでいないようですので、S-038 の解答から以下の記述を削除した方がより問題文に沿った解答になると思いました。

```sql
ORDER BY customer_id
```

非常に些細な点ですが、ご確認いただけると幸いです。

**Comment by KazuhiroM** [comment]
イシューの投稿ありがとうございます！動作確認のために入れたソートが残っているのかもしれません。

確認して適宜対応します。

**Comment by KazuhiroM** [comment]
対応しました

クローズいたしますmm
