### ISSUE TITLE
windows で環境構築中　　ERROR: Service 'notebook' failed to build:

### ISSUE THREAD

**Issue by kddings** [The-Japan-DataScientist-Society/100knocks-preprocess#9]
windows で環境構築中に
ERROR: Service 'notebook' failed to build: The command '/bin/bash -o pipefail -c apt-get update' returned a non-zero code: 100

のエラーが出てしまいます対処方法はありますでしょうか？

**Comment by KazuhiroM** [comment]
不具合の指摘などは対応させていただいているのですが、利用に関する個別の質問については対応ができない点、ご了承ください。
